#version: '3'

services:
 # thredds-quickstart:
  #  image: unidata/thredds-docker:5.8
   # ports:
    #  - "80:8080"
     # - "443:8443"
      #- "8443:8443"

  thredds-production:
    image: unidata/thredds-docker:5.8
    ports:
      - "80:8080"
      - "443:8443"
      - "8443:8443"
    container_name: thredds
    volumes:
      - ~/thredds-prod/tomcat-logs/:/usr/local/tomcat/logs/
      - ~/thredds-prod/thredds-logs/:/usr/local/tomcat/content/thredds/logs/
      - ~/thredds-docker/files/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ~/thredds-prod/thredds-content:/usr/local/tomcat/content/thredds
      - ~/thredds-prod/data:/data
    env_file:
      - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"

  ###
  # TDM
  # Not strictly part of this repo, but useful to have around
  # https://github.com/Unidata/tdm-docker
  ###

#  tdm:
 #   image: unidata/tdm-docker:5.8
  #  container_name: tdm
   # volumes:
    #  - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
     # - /path/to/your/data/directory1:/path/to/your/data/directory1
    # env_file:
    #  - "compose${THREDDS_COMPOSE_ENV_LOCAL}.env"
