#+options: ':nil *:t -:t ::t <:t H:4 \n:nil ^:t arch:headline author:t
#+options: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+options: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+options: auto-id:t

#+title: readme
#+date: <2023-04-24 Mon>
#+author: Julien Chastang
#+email: chastang@ucar.edu
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 28.2 (Org mode 9.7-pre)

#+PROPERTY: header-args :eval no :results none

#+STARTUP: overview

* Setup                                                            :noexport:
  :PROPERTIES:
  :CUSTOM_ID: h-F864C586
  :END:

#+BEGIN_SRC emacs-lisp :eval yes
  (setq org-confirm-babel-evaluate nil)
#+END_SRC

Publishing

#+BEGIN_SRC emacs-lisp :eval yes
  (setq base-dir (concat (projectile-project-root) ".org"))

  (setq pub-dir (projectile-project-root))

  (setq org-publish-project-alist
        `(("unidata-thredds-readme"
            :base-directory ,base-dir
            :recursive t
            :base-extension "org"
            :publishing-directory ,pub-dir
            :publishing-function org-gfm-publish-to-gfm)))
#+END_SRC

* Unidata THREDDS Docker
:PROPERTIES:
:CUSTOM_ID: h-D1C45A11
:END:

Dockerized [[https://www.unidata.ucar.edu/software/tds/][THREDDS]].

** Introduction
:PROPERTIES:
:CUSTOM_ID: h-F96AB5F8
:END:

This repository contains files necessary to build and run a THREDDS Docker container. The Unidata THREDDS Docker images associated with this repository are [[https://hub.docker.com/r/unidata/thredds-docker/][available on DockerHub]].
The current target for this branch and image is TDS ~5.10-SNAPSHOT~ on Tomcat 11 and JDK 17.

*** What's New For TDS 5.10
:PROPERTIES:
:CUSTOM_ID: h-B6E0F7DE
:END:

This release modernizes the THREDDS Docker image for TDS 5.10.

- *TDS 5.10, Tomcat 11, and JDK 17:* The image now targets TDS ~5.10-SNAPSHOT~ and is based on ~unidata/tomcat-docker:11-jdk17~.

- *Updated native libraries:* The bundled native dependencies have been updated to HDF5 1.14.6, zlib 1.3.2, and netCDF-C 4.10.1.

- *Hardened Tomcat runtime:* The image inherits the parent container's privilege dropping and configurable runtime UID/GID support. Tomcat installation and configuration files remain protected, while the TDS content tree (=${CATALINA_HOME}/content=) is explicitly writable. Site-specific Tomcat configuration files should be mounted read-only.

- *TDM separated from this image*: The bundled TDM service and configuration have been removed. TDM is maintained separately in the  [[https://github.com/Unidata/tdm-docker][tdm-docker]] repository.
  
- *Docker Swarm support removed:* The legacy Swarm configuration and documentation have been removed.

- *Persistent Java preferences:* Java Preferences storage now resides beneath the TDS content root so that it follows the same writable and persistent storage model as other TDS content.

- *Faster development builds:* Image builds can optionally skip compilation of the native libraries with ~--build-arg SKIP_NATIVE_BUILD=true~. This option is intended for development and testing, not production images.

*** Quickstart
:PROPERTIES:
:CUSTOM_ID: h-C733CD96
:END:

#+begin_src sh
  docker run -d -p 80:8080 unidata/thredds-docker:<version>
#+end_src

** Versions
   :PROPERTIES:
   :CUSTOM_ID: h-AF015058
   :END:

See tags listed [[https://hub.docker.com/r/unidata/thredds-docker/tags][on dockerhub]]. Our security protocols have become stricter, and older images must be removed due to potential links with high profile CVEs. We strive to maintain the security of this project's DockerHub images by updating them with the latest upstream improvements. If you have any concerns in this area, please email us at [[mailto:security@unidata.ucar.edu][security@unidata.ucar.edu]] to bring them to our attention.

** Prerequisites
:PROPERTIES:
:CUSTOM_ID: h-1EB18866
:END:

Before you begin using this Docker container project, make sure your system has Docker installed. Docker Compose is optional but recommended.
** Installation
:PROPERTIES:
:CUSTOM_ID: h-A767C942
:END:

You can either pull the image from DockerHub with:

#+begin_src sh
  docker pull unidata/thredds-docker:<version>
#+end_src

Or you can build it yourself with:

  1. **Clone the repository**: ~git clone https://github.com/Unidata/thredds-docker.git~
  2. **Navigate to the project directory**: ~cd thredds-docker~
  3. **Build the Docker image**: ~docker build -t thredds-docker:<version> .~
** Usage
:PROPERTIES:
:CUSTOM_ID: h-58EC333B
:END:
*** Memory
    :PROPERTIES:
    :CUSTOM_ID: h-069B9D1E
    :END:

Tomcat web applications and the TDS can require large amounts of memory to run. This container is setup to run Tomcat with a default [[file:files/javaopts.sh][4 gigabyte memory allocation]]. When running this container, ensure your VM or hardware can accommodate this memory requirement.

*** Docker compose
   :PROPERTIES:
   :CUSTOM_ID: h-1C0CB7E8
   :END:

To run the THREDDS Docker container, beyond a basic Docker setup, we recommend installing [[https://docs.docker.com/compose/][docker-compose]]. ~docker-compose~ serves two purposes:

1. Reduce headaches involving unwieldy ~docker~ command lines where you are running ~docker~ with multiple volume mounts and port forwards. In situations like these, ~docker~ commands become difficult to issue and read. Instead, the lengthy ~docker~ command is captured in a ~docker-compose.yml~ that is easy to read, maintain, and can be committed to version control.

2. Capture the ports, volume mounts, and environment settings used by the TDS deployment.

However, ~docker-compose~ use is not mandatory. There is an example [[https://github.com/Unidata/thredds-docker/blob/master/docker-compose.yml][docker-compose.yml]] in this repository.

**** Running the TDS
    :PROPERTIES:
    :CUSTOM_ID: h-E18F7CAE
    :END:

Once you have completed your setup you can run the container with:

#+BEGIN_SRC sh
  docker-compose up -d thredds-production
#+END_SRC

The output of such command should be something like:

#+BEGIN_EXAMPLE
  Creating thredds
#+END_EXAMPLE

**** Stopping the TDS
    :PROPERTIES:
    :CUSTOM_ID: h-82936877
    :END:

To stop this container:

#+BEGIN_SRC sh
  docker-compose stop thredds-production
#+END_SRC

**** Delete TDS Container
    :PROPERTIES:
    :CUSTOM_ID: h-63682079
    :END:

To clean the slate and remove the container (not the image, the container):

#+BEGIN_SRC sh
  docker-compose rm -f thredds-production
#+END_SRC

*** Upgrading
    :PROPERTIES:
    :CUSTOM_ID: h-73D8E285
    :END:

Upgrading to a newer version of the container is easy. Simply stop the container via ~docker~ or ~docker-compose~, followed by

#+BEGIN_SRC sh
  docker pull unidata/thredds-docker:<version>
#+END_SRC

and restart the container.  Refer to the new version from the command line or in the ~docker-compose.yml~.

*** Check What is Running
   :PROPERTIES:
   :CUSTOM_ID: h-E74AFAFF
   :END:
**** curl
    :PROPERTIES:
    :CUSTOM_ID: h-B9BDE649
    :END:

At this point you should be able to do:

#+BEGIN_SRC sh
  curl localhost:80/thredds/catalog/catalog.html
  # or whatever port you mapped to outside the container in the docker-compose.yml
#+END_SRC

and get back a response that looks something like

#+BEGIN_EXAMPLE
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>TDS Catalog</title>
    <!-- Common metadata and styles. -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <!-- if webcrawler finds this page (say, from sitemap.xml), tell it to not follow the links -->
    <meta name="robots" content="nofollow" />

    <link rel="stylesheet" href="/thredds/tds.css" type="text/css"><link rel="stylesheet" href="/thredds/tds.css" type="text/css"><link rel="stylesheet" href="/thredds/tdsCat.css" type="text/css">

    <script type="text/javascript">
    document.getElementById("header-buffer").style.height = document.getElementById("header").clientHeight + "px";
    document.getElementById("footer-buffer").style.height = document.getElementById("footer").clientHeight + "px";
  </script>
  </head>
  ...
  </html>
#+END_EXAMPLE

**** docker ps
    :PROPERTIES:
    :CUSTOM_ID: h-F9E31E12
    :END:

If you encounter a problem there, you can also:

#+BEGIN_SRC sh
  docker ps
#+END_SRC

which should give you output that looks something like this:

#+BEGIN_EXAMPLE
  CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS              PORTS                                                                 NAMES
  6c256c50a6cf        unidata/thredds-docker:<version>  "/entrypoint.sh star"    6 minutes ago       Up 6 minutes        0.0.0.0:80->8080/tcp   threddsdocker_thredds-quickstart_1
#+END_EXAMPLE

to obtain the ID of the running TDS container. You can enter the container with:

#+BEGIN_SRC sh
  docker exec -it <ID> bash
#+END_SRC

Use ~curl~ *inside* the container to verify the TDS is running:

#+BEGIN_SRC sh
  curl localhost:8080/thredds/catalog/catalog.html
#+END_SRC

you should get a response that looks something like:

#+BEGIN_EXAMPLE
  <!DOCTYPE html>
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>TDS Catalog</title>
    <!-- Common metadata and styles. -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <!-- if webcrawler finds this page (say, from sitemap.xml), tell it to not follow the links -->
    <meta name="robots" content="nofollow" />

    <link rel="stylesheet" href="/thredds/tds.css" type="text/css"><link rel="stylesheet" href="/thredds/tds.css" type="text/css"><link rel="stylesheet" href="/thredds/tdsCat.css" type="text/css">

    <script type="text/javascript">
    document.getElementById("header-buffer").style.height = document.getElementById("header").clientHeight + "px";
    document.getElementById("footer-buffer").style.height = document.getElementById("footer").clientHeight + "px";
  </script>
  </head>
  ...
  </html>
#+END_EXAMPLE

** Configuration
:PROPERTIES:
:CUSTOM_ID: h-817EB413
:END:
*** Docker compose
:PROPERTIES:
:CUSTOM_ID: h-F95DCC06
:END:
**** Basic
    :PROPERTIES:
    :CUSTOM_ID: h-0351DF56
    :END:

Define directory and file paths for log files, Tomcat, THREDDS, and data in [[https://github.com/Unidata/thredds-docker/blob/master/docker-compose.yml][docker-compose.yml]] for the ~thredds-production~ image.

**** Environment Variables
    :PROPERTIES:
    :CUSTOM_ID: h-D856FFF9
    :END:

This project contains a ~docker-compose~ [[https://docs.docker.com/compose/compose-file/#envfile][environment file]] named ~compose.env~. This file contains default values for ~docker-compose~ to launch the TDS. You can configure these parameters:

#+BEGIN_EXAMPLE
  | Parameter                   | Environment Variable  | Default Value                |
  |-----------------------------+-----------------------+------------------------------|
  | TDS Content Root            | TDS_CONTENT_ROOT_PATH | /usr/local/tomcat/content    |
  | TDS JVM Max Heap Size (xmx) | THREDDS_XMX_SIZE      | 4G                           |
  | TDS JVM Min Heap Size (xms) | THREDDS_XMS_SIZE      | 4G                           |
  | Tomcat User ID              | TOMCAT_USER_ID        | 1000                         |
  | Tomcat Group ID             | TOMCAT_GROUP_ID       | 1000                         |
#+END_EXAMPLE

If you wish to update your configuration, you can either update the ~compose.env~ file or create your own environments file by copying ~compose.env~. If using your own file, you can export the suffix of the file name into an environment variable named ~THREDDS_COMPOSE_ENV_LOCAL~. Also see the ~env_file~ key in [[https://github.com/Unidata/thredds-docker/blob/master/docker-compose.yml][docker-compose.yml]].

For example:

#+BEGIN_SRC sh
  cp compose.env compose_local.env
  export THREDDS_COMPOSE_ENV_LOCAL=_local
  < edit compose_local.env >
  docker-compose up thredds-production
#+END_SRC

*** Tomcat
    :PROPERTIES:
    :CUSTOM_ID: h-A82C8590
    :END:

This image derives from [[https://github.com/Unidata/tomcat-docker/tree/11-jdk17][~unidata/tomcat-docker:11-jdk17~]], which provides Tomcat 11 on JDK 17. Startup, privilege dropping, runtime UID/GID handling, and Tomcat's standard writable directories are inherited from that parent. The Tomcat installation itself, including ~conf~, ~bin~, ~lib~, and ~webapps~, remains protected. Supply site-specific replacement configuration as individual read-only file mounts rather than making Tomcat configuration directories writable. See the [[https://github.com/Unidata/tomcat-docker/tree/11-jdk17][parent repository]] for the complete runtime contract.

*** Java Configuration Options
    :PROPERTIES:
    :CUSTOM_ID: h-609AFE2D
    :END:

The Java configuration options (~JAVA_OPTS~) are configured in =${CATALINA_HOME}/bin/javaopts.sh= (see [[file:files/javaopts.sh][javaopts.sh]]) inside the container. Note this file is copied inside the container during the Docker build. See the ~docker-compose~ section above for configuring some of the environment variables of this file.

*** Configurable Tomcat UID and GID
    :PROPERTIES:
    :CUSTOM_ID: h-350BEF91
    :END:

~TOMCAT_USER_ID~ and ~TOMCAT_GROUP_ID~ default to ~1000:1000~ and may be overridden. [[https://github.com/Unidata/tomcat-docker#configurable-tomcat-uid-and-gid][See the parent container]] for details.

*** THREDDS
    :PROPERTIES:
    :CUSTOM_ID: h-D046D64C
    :END:

To mount your own ~content/thredds~ directory with ~docker-compose.yml~:

#+BEGIN_SRC yaml
    volumes:
      - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
#+END_SRC

=${CATALINA_HOME}/content= is explicitly designated as an additional writable directory for TDS. At container startup, the parent prepares this tree for =TOMCAT_USER_ID:TOMCAT_GROUP_ID=; bind-mounted content may therefore be recursively re-owned to that UID/GID. Persistent Java Preferences storage is also located beneath this writable content tree.

If you just want to change a few files, you can mount them individually. Please note that the *THREDDS cache is stored in the content directory*. If you choose to mount individual files, you should also mount a cache directory.

#+BEGIN_SRC yaml
  volumes:
    - /path/to/your/tomcat/logs/:/usr/local/tomcat/logs/
    - /path/to/your/thredds/logs/:/usr/local/tomcat/content/thredds/logs/
    - /path/to/your/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
    - /path/to/your/thredds/directory:/usr/local/tomcat/content/thredds
    - /path/to/your/data/directory1:/path/to/your/data/directory1
    - /path/to/your/data/directory2:/path/to/your/data/directory2
    - /path/to/your/server.xml:/usr/local/tomcat/conf/server.xml:ro
    - /path/to/your/web.xml:/usr/local/tomcat/conf/web.xml:ro
    - /path/to/your/keystore.p12:/usr/local/tomcat/conf/keystore.p12:ro
#+END_SRC

*** HTTPS
    :PROPERTIES:
    :CUSTOM_ID: h-5A4BABB7
    :END:

By default, Tomcat serves HTTP on port 8080. To configure Tomcat to serve HTTPS directly, see the parent container's  [[https://github.com/Unidata/tomcat-docker#https][HTTPS documentation]].

*** Users
    :PROPERTIES:
    :CUSTOM_ID: h-E20C4A41
    :END:

The bundled [[file:files/tomcat-users.xml][tomcat-users.xml]] declares the ~tdsConfig~, ~tdsMonitor~, and ~tdsTrigger~ roles. To use protected TDS functionality, provide a site-specific ~tomcat-users.xml~ as described below.

*** Configuring TDS Roles
:PROPERTIES:
:CUSTOM_ID: h-D90F09BB
:END:

The TDS uses the Tomcat roles ~tdsConfig~, ~tdsMonitor~, and ~tdsTrigger~ to control access to [[https://docs.unidata.ucar.edu/tds/current/userguide/remote_management_ref.html][protected administrative functionality]]. Assign only the roles a user requires.

For example, create a site-specific ~tomcat-users.xml~ containing a user and the desired roles:

#+begin_src xml
  <tomcat-users>
    <role rolename="tdsConfig"/>
    <role rolename="tdsMonitor"/>
    <role rolename="tdsTrigger"/>

    <user username="tds-admin"
          password="DIGESTED_PASSWORD"
          roles="tdsConfig,tdsMonitor,tdsTrigger"/>
  </tomcat-users>
#+end_src

Generate ~DIGESTED_PASSWORD~ using the SHA-512 password procedure described in the [[https://github.com/Unidata/tomcat-docker#digested-passwords][parent Tomcat container documentation]]. Mount the completed file read-only into the container:

#+begin_src yaml
  volumes:
    - /path/to/your/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:ro
#+end_src

Restart the container after changing ~tomcat-users.xml~. Administrative TDS endpoints should be exposed only over HTTPS.

*** ncSOS
    :PROPERTIES:
    :CUSTOM_ID: h-F2383FF5
    :END:

To enable ncSOS in ~threddsConfig.xml~, uncomment the ~NCSOS~ block and set its ~allow~ value to ~true~.

** netCDF
:PROPERTIES:
:CUSTOM_ID: h-90623D0B
:END:

This Docker project includes the installation of the netCDF-c project to allow for the downloading of netCDF files using the  [[https://docs.unidata.ucar.edu/tds/current/userguide/netcdf_subset_service_ref.html][NetCDF Subset Service]].

** Maintainers
:PROPERTIES:
:CUSTOM_ID: h-1559ED59
:END:

What to do when a version of the THREDDS data server is released?

- Update the ~Dockerfile~ with the ~war~ file corresponding to the new version of the TDS. E.g.,

#+begin_src shell
  ENV THREDDS_WAR_URL https://downloads.unidata.ucar.edu/tds/5.10/thredds-5.10-SNAPSHOT.war
#+end_src

- Check with the netCDF group if versions of HDF5, zlib, and netCDF referenced in the ~Dockerfile~ need to be updated.
- Update the TDS version in ~docker-compose.yml~.
- Update the ~CHANGELOG.md~ documenting updates to this project (not the TDS) since the last release.
- Create a new git branch corresponding to this version of the TDS (e.g., ~5.10-SNAPSHOT~).
- Push the new branch out to the ~Unidata/thredds-docker~ GitHub repository. This branch will remain frozen in time going forward. Any subsequent updates to this project should happen on the the ~latest~ branch. The only exception to this convention is if there is a critical (e.g., security related) update that needs to be applied to the ~Dockerfile~ and associated files and eventually to the image (see below)
- Build a docker image corresponding to the new version of the TDS (e.g., on the Docker build machine on Jetstream). E.g., ~docker build -t unidata/thredds-docker:5.10-SNAPSHOT~.
- Test to ensure the image works.
- Push it out DockerHub e.g., ~docker push unidata/thredds-docker:5.10-SNAPSHOT~.
- Note that this image *does not* remain frozen in time for two reasons.
  1. It can get rebuilt time and again as upstream image updates need to be incorporated into this THREDDS image. It may be confusing for a versioned image to evolve, but it is the convention in Dockerland.
  2. It can get rebuilt in the rare case the Dockerfile or associated files are updated on the branch as mentioned earlier.

** Citation
   :PROPERTIES:
   :CUSTOM_ID: h-0BAA13E6
   :END:

In order to cite this project, please simply make use of the Unidata THREDDS Data Server DOI: doi:10.5065/D6N014KG https://doi.org/10.5065/D6N014KG

** Support
   :PROPERTIES:
   :CUSTOM_ID: h-7D1176D3
   :END:

If you have a question or would like support for this THREDDS Docker container, consider [[https://github.com/Unidata/thredds-docker/issues][submitting a GitHub issue]]. Alternatively, you may wish to start a discussion on the THREDDS Community mailing list: [[mailto:thredds@unidata.ucar.edu][thredds@unidata.ucar.edu]].

For general TDS questions, please see the [[https://www.unidata.ucar.edu/software/tds/#help][THREDDS support page]].
