name: Docker Image CI

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
#

# Leave out specific branches so this same workflow can be used on any branch
on: [ push, pull_request ]

jobs:

  buildAndTest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the commit that triggered the workflow
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag unidata/thredds-docker:latest
    - name: Run the container
      run: |
        docker run --name thredds \
        -v $(pwd)/.github/testScripts:/testScripts \
        -d \
        -p 8080:8080 \
        unidata/thredds-docker:latest
    # Give chance for TDS to fire up
    - name: Wait and listen for TDS to fire up
      run: nc -z -w300 127.0.0.1 8080
    - run: |
        for i in {1..5}; do curl -o /dev/null http://127.0.0.1:8080/thredds/catalog.html && break || \
        (echo sleeping 15... && sleep 15); done
    - name: Run test script
      run: ./.github/testScripts/test.sh
